// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  describe("finances", function() {
    beforeEach(function() {
      return finances.reset();
    });
    it('should be groovy', function() {
      return expect(finances).toBeDefined();
    });
    it('should track users', function() {
      var a1, a2, i1;
      a1 = new finances.Account('Fred');
      a2 = new finances.Account('Dafny');
      i1 = new finances.Item('dinner', 80);
      a1.uses(i1);
      a2.uses(i1);
      expect(__indexOf.call(finances.getUsers(i1), a1) >= 0).toBe(true);
      return expect(__indexOf.call(finances.getUsers(i1), a2) >= 0).toBe(true);
    });
    return it('should track payments', function() {
      var a1, a2, accounts, i1, p, _i, _len, _ref;
      a1 = new finances.Account('Fred');
      a2 = new finances.Account('Dafny');
      i1 = new finances.Item('dinner', 80);
      a1.pays(i1, 50);
      a2.pays(i1, 50);
      _ref = finances.getPayments(i1);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        p = _ref[_i];
        accounts = p.account;
      }
      expect(__indexOf.call(accounts, a1) >= 0);
      return expect(__indexOf.call(accounts, a2) >= 0);
    });
  });

}).call(this);
